# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image with Alpine for a smaller image size
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use a separate image for the runtime to keep the image lightweight
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy the build output and package.json to the runtime image
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./

# Install only production dependencies
RUN npm install --only=production

# Set environment variables (ensure these are set as needed in a secure manner)
ENV SSH_HOST=your.remote.host \
    SSH_USER=your_ssh_user \
    SSH_PRIVATE_KEY_PATH=your_SSH_PRIVATE_KEY_PATH \
    RAILS_WORKING_DIR=/path/to/rails/app/root

# Command to run the application
CMD ["node", "build/index.js"]
